### ISSUE TITLE
Expander not collaped

### ISSUE THREAD

**Issue by thimmy687** [OTHRegensburgDT/dt_proj_ws16_17#10]
Hey @BerndNK kannst du mal schauen, an welche stelle ich den Expander legen muss, damit er richtig arbeitet?

![image](https://cloud.githubusercontent.com/assets/7715216/20749847/51c011a8-b6f4-11e6-8951-e86b6c7ef17a.png)

**Comment by thimmy687** [comment]
Liegt im ItemsControl aktuell

**Comment by thimmy687** [comment]
Hab die Lösung, muss nur ein ItemsControl in das ItemsControl legen

**Comment by thimmy687** [comment]
Geht doch nicht so einfach, wegen dem Binding

**Comment by BerndNK** [comment]
Mach als ItemsPanel ein StackPanel Orientation = Vertical, statt einem UniformGrid

**Comment by thimmy687** [comment]
Nein immer noch nicht
